<popupError@Popup>
    auto_dismiss: False
    title: "Error"
    size: 400, 200
    size_hint: None, None
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            padding: 10
            Label:
                text: "%s" % app.root.error
                multiline: True
        BoxLayout:
            padding: 10
            Button:
                text: "Close"
                on_press: root.dismiss()

