<report@Popup>
    auto_dismiss: False
    title: "Report"
    size_hint: .75, .75
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            padding: 10
            TextInput:
                id: reportText
        BoxLayout:
            padding: self.width * .25, self.height * .25, self.width * .25, self.height * .25
            size_hint: 1, .5
            Button:
                text: "Submit"
                on_press: root.submit()